<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-8GVID27" ignored="0" name="Chrome Test" tests="11" failures="1" timestamp="02 Jun 2019 20:11:36 GMT" time="49.564" errors="0">
  <testcase name="testCase" time="0.006" classname="Framework.TestNG.TestNGBasics"/>
  <testcase name="testCase2" time="0.002" classname="Framework.TestNG.TestNGBasics"/>
  <testcase name="clickOnShopingCart" time="2.685" classname="Framework.TestNG.Practice1"/>
  <testcase name="testTheLoginBtn" time="2.981" classname="Framework.TestNG.LoginTest"/>
  <testcase name="loginWithIncPassANDEmail" time="3.084" classname="Framework.TestNG.Practice1"/>
  <testcase name="testLogIn1" time="3.079" classname="Framework.TestNG.Practice1"/>
  <testcase name="testLogIn2" time="2.814" classname="Framework.TestNG.Practice1"/>
  <testcase name="testLogIn3" time="3.4" classname="Framework.TestNG.Practice1"/>
  <testcase name="testLogIn" time="3.551" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="The app did not log in expected [My Account] but found [Account Login]">
      <![CDATA[java.lang.AssertionError: The app did not log in expected [My Account] but found [Account Login]
at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:50)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="hpLaptop" time="6.259" classname="Framework.TestNG.Practice2"/>
  <testcase name="macBook" time="2.656" classname="Framework.TestNG.Practice2"/>
</testsuite> <!-- Chrome Test -->
